const body = document.querySelector("body");
const headerPage = document.createElement("h1");
headerPage.innerHTML = "Which one is your favorite?";
const chooseMain = document.createElement("div");
chooseMain.className = "chooseMain";
const chooseLeft = document.createElement("div");
chooseLeft.className = "chooseLeft";
const chooseRight = document.createElement("div");
chooseRight.className = "chooseRight";
const imageDivThis = document.createElement("div");
imageDivThis.className = "image-divs";
const imageDivThat = document.createElement("div");
imageDivThat.className = "image-divs";
const thisButton = document.createElement("button");
thisButton.innerHTML = "THIS!";
const thatButton = document.createElement("button");
thatButton.innerHTML = "THAT!";
const orDiv = document.createElement("div");
orDiv.className = "orDiv";
orDiv.innerHTML = "<p>OR</p>";
chooseLeft.append(imageDivThis, thisButton);
chooseRight.append(imageDivThat, thatButton);
chooseMain.append(chooseLeft, chooseRight, orDiv);
const leaderBoard = document.createElement("div");
leaderBoard.className = "leaderboard";
body.append(headerPage, chooseMain, leaderBoard);
